name: klasifikasi_makanan_minang
description: "Aplikasi klasifikasi makanan Minangkabau"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  http: ^1.1.3
  dio: ^5.3.2
  provider: ^6.1.1
  image_picker: ^1.1.0
  camera: ^0.10.5
  image: ^4.0.17
  flutter_image_compress: ^2.4.0
  permission_handler: ^11.0.1
  http_parser: ^4.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  pull_to_refresh: ^2.0.0
  intl: ^0.18.1
  logger: ^1.4.0
  mocktail: ^1.0.0
  golden_toolkit: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon-minang.png
    - .env
